spring:
  application:
    name: ms-digitalfix-report
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/${AZURE_TENANT_ID}/
server:
  port: 8083
